### ISSUE TITLE
NoSuchMethodError: scala.Product.$init$

### ISSUE THREAD

**Issue by markmcwiggins** [G-Research/spark-extension#117]
I ran:

    spark-submit --packages uk.co.gresearch.spark:spark-extension_2.13:2.2.0-3.3 step4.py

And the result was:

	Traceback (most recent call last):
	  File "/home/vn53el7/msc-dataflow/data_pipelines/keyword.nope/tasks/step4.py", line 79, in <module>
	    diffdf = sortdf.diff(sort_u_df, "SideBySide")
	  File "/home/vn53el7/.ivy2/jars/uk.co.gresearch.spark_spark-extension_2.13-2.2.0-3.3.jar/gresearch/spark/diff/__init__.py", line 490, in diff
	  File "/home/vn53el7/.ivy2/jars/uk.co.gresearch.spark_spark-extension_2.13-2.2.0-3.3.jar/gresearch/spark/diff/__init__.py", line 425, in diff
	  File "/home/vn53el7/.ivy2/jars/uk.co.gresearch.spark_spark-extension_2.13-2.2.0-3.3.jar/gresearch/spark/diff/__init__.py", line 358, in _to_java
	  File "/home/vn53el7/.ivy2/jars/uk.co.gresearch.spark_spark-extension_2.13-2.2.0-3.3.jar/gresearch/spark/diff/__init__.py", line 343, in _to_java
	  File "/usr/lib/spark/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py", line 1525, in __call__
	  File "/usr/lib/spark/python/lib/pyspark.zip/pyspark/sql/utils.py", line 63, in deco
	  File "/usr/lib/spark/python/lib/py4j-0.10.7-src.zip/py4j/protocol.py", line 328, in get_return_value
	py4j.protocol.Py4JJavaError: An error occurred while calling None.uk.co.gresearch.spark.diff.DiffOptions.
	: java.lang.NoSuchMethodError: scala.Product.$init$(Lscala/Product;)V
		at uk.co.gresearch.spark.diff.DiffOptions.<init>(DiffOptions.scala:80)
		at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
		at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
		at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
		at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
		at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:247)
		at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
		at py4j.Gateway.invoke(Gateway.java:238)
		at py4j.commands.ConstructorCommand.invokeConstructor(ConstructorCommand.java:80)
		at py4j.commands.ConstructorCommand.execute(ConstructorCommand.java:69)
		at py4j.GatewayConnection.run(GatewayConnection.java:238)
		at java.lang.Thread.run(Thread.java:748)

And it isn't the **SIdebySide** parameter, as I get the same result with that in place and missing.

Thanks.

**Comment by EnricoMi** [comment]
This looks like a Scala version mismatch. Please run

    spark-submit --version

and paste the output here.

**Comment by markmcwiggins** [comment]
Not easy to cut/paste but looks like you're right:

Spark 2.4.8
using Scala version 2.11.12

Can this still work if I download this Scala version?

------- Original Message -------

**Comment by EnricoMi** [comment]
If you install a 2.11 Scala, then you can use spark-extension version 1.4.0 with Spark 2.4.

    uk.co.gresearch.spark:spark-extension_2.12:1.4.0-2.4'

For documentation of 1.4.0, you should look here: https://github.com/G-Research/spark-extension/tree/v1.4.0

Note that Spark 2.4 is not supported after 1.4.0.
