### ISSUE TITLE
NoSuchMethodError: org.apache.spark.sql.internal.SQLConf$.get() Error

### ISSUE THREAD

**Issue by Protocol-X** [G-Research/spark-extension#30]
I have tried all over your versions for Scala 2.11 and everyone gives this error when trying to use diff.
I have the apache packages in the pom and use them for spark all the time with no issues.

xyz_data.diff(xyz_data2)

`Exception in thread "streaming-job-executor-0" java.lang.NoSuchMethodError: org.apache.spark.sql.internal.SQLConf$.get()Lorg/apache/spark/sql/internal/SQLConf;
	at uk.co.gresearch.spark.diff.package$.handleConfiguredCaseSensitivity(package.scala:170)
	at uk.co.gresearch.spark.diff.DiffOptions.<init>(DiffOptions.scala:93)
	at uk.co.gresearch.spark.diff.DiffOptions$.<init>(DiffOptions.scala:216)
	at uk.co.gresearch.spark.diff.DiffOptions$.<clinit>(DiffOptions.scala)
	at uk.co.gresearch.spark.diff.Diff$.<init>(Diff.scala:305)
	at uk.co.gresearch.spark.diff.Diff$.<clinit>(Diff.scala)
	at uk.co.gresearch.spark.diff.package$DatasetDiff.diff(package.scala:86)
	at com.xyz.sh.spark.ds.app.XYZProducer$$anonfun$execute$7.apply(XYZProducer.scala:750)
	at com.xyz.sh.spark.ds.app.XYZProducer$$anonfun$execute$7.apply(XYZProducer.scala:713)
	at org.apache.spark.streaming.dstream.DStream$$anonfun$foreachRDD$1$$anonfun$apply$mcV$sp$3.apply(DStream.scala:627)
	at org.apache.spark.streaming.dstream.DStream$$anonfun$foreachRDD$1$$anonfun$apply$mcV$sp$3.apply(DStream.scala:627)
	at org.apache.spark.streaming.dstream.ForEachDStream$$anonfun$1$$anonfun$apply$mcV$sp$1.apply$mcV$sp(ForEachDStream.scala:51)
	at org.apache.spark.streaming.dstream.ForEachDStream$$anonfun$1$$anonfun$apply$mcV$sp$1.apply(ForEachDStream.scala:51)
	at org.apache.spark.streaming.dstream.ForEachDStream$$anonfun$1$$anonfun$apply$mcV$sp$1.apply(ForEachDStream.scala:51)
	at org.apache.spark.streaming.dstream.DStream.createRDDWithLocalProperties(DStream.scala:415)
	at org.apache.spark.streaming.dstream.ForEachDStream$$anonfun$1.apply$mcV$sp(ForEachDStream.scala:50)
	at org.apache.spark.streaming.dstream.ForEachDStream$$anonfun$1.apply(ForEachDStream.scala:50)
	at org.apache.spark.streaming.dstream.ForEachDStream$$anonfun$1.apply(ForEachDStream.scala:50)
	at scala.util.Try$.apply(Try.scala:192)
	at org.apache.spark.streaming.scheduler.Job.run(Job.scala:39)
	at org.apache.spark.streaming.scheduler.JobScheduler$JobHandler$$anonfun$run$1.apply$mcV$sp(JobScheduler.scala:256)
	at org.apache.spark.streaming.scheduler.JobScheduler$JobHandler$$anonfun$run$1.apply(JobScheduler.scala:256)
	at org.apache.spark.streaming.scheduler.JobScheduler$JobHandler$$anonfun$run$1.apply(JobScheduler.scala:256)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
	at org.apache.spark.streaming.scheduler.JobScheduler$JobHandler.run(JobScheduler.scala:255)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
`

**Comment by EnricoMi** [comment]
Is that code in a public repo? Or can you provide me the `pom.xml` so I can reproduce this?

**Comment by Protocol-X** [comment]
[pom.zip](https://github.com/G-Research/spark-extension/files/5747956/pom.zip)

Here is the requested pom.  The version of your library is an older one, but as i mentioned i have tried all versions for scala 2.11

**Comment by EnricoMi** [comment]
You are using a very old Spark version, 2.1.1 is 3 minor versions behind 2.4. The spark-extension package is compiled against 2.4 and only binary-compatible with that minor version. Earlier versions are not supported.

Have you tried it with Spark 2.4.x?

**Comment by Protocol-X** [comment]
I did not, Per the naming convention I thought it supported from 1.3.2 and higher.  Sorry for the misunderstanding.

**Comment by EnricoMi** [comment]
Which naming convention are you referring to?

**Comment by Protocol-X** [comment]
In the maven repo, it uses a "-" instead of an "_" so i misinerperated it as a min/max spark version and not a library/spark version.

**Comment by EnricoMi** [comment]
I have added some remarks to the readme: https://github.com/g-research/spark-extension#using-spark-extension

Please let me know if this clarifies things and would have helped. Also please try with Spark 2.4 and let me know if the package works for you with that version. Thanks a lot!
